**Tutorial style and structure credit:**<br/>
[sentdex](https://www.youtube.com/c/sentdex/featured)

### Basic Neuron
single input, single neuron

In [1]:
inputs = [4.5, 2.3, -7.4]
weights = [1.7, 5.9, 3.6]
bias = 2

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias
print(output)

-3.4200000000000017


------------------------------------------------------------------------------------------------

### Basic Layer
multiple inputs, multiple neurons<br/>
densely connected, all inputs go to all neurons<br/>
unique sets of weights and biases for each neuron, inputs remain the same

In [27]:
inputs = [4.5, 2.3, -7.4, 1.5]

weights1 = [0.17, 0.59, 0.36, -0.66]
weights2 = [0.23, -0.34, 0.45, 0.12]
weights3 = [-0.67, 0.78, 0.14, 0.25]

bias1 = 2
bias2 = 1
bias3 = 3.1

output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
          inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,
          inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3]
print(output)

[0.46799999999999975, -1.8969999999999998, 1.2179999999999995]


----------------------------

### Clean Code

In [28]:
inputs = [4.5, 2.3, -7.4, 1.5]

weights = [[0.17, 0.59, 0.36, -0.66],
           [0.23, -0.34, 0.45, 0.12],
           [-0.67, 0.78, 0.14, 0.25]]

biases = [2, 1, 3.1]

layer_output=[]  # output of one layer of neurons
for i in range(len(weights)): # taking weights row-wise
    neuron_output=0.0  # output of single neuron in said layer
    for j in range(len(weights[i])):
        neuron_output = neuron_output + inputs[j]*weights[i][j]
    neuron_output = round((neuron_output + biases[i]),3)
    layer_output.append(neuron_output)

print(layer_output)

[0.468, -1.897, 1.218]


---------------------------

### Dot Product

In [29]:
import numpy as np

In [31]:
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

output = np.dot(inputs, weights) + bias
print(output)

# sanity check
output2 = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + bias
print("check: ", output2)

4.8
check:  4.8


In [42]:
inputs = [4.5, 2.3, -7.4, 1.5]

weights = [[0.17, 0.59, 0.36, -0.66],
           [0.23, -0.34, 0.45, 0.12],
           [-0.67, 0.78, 0.14, 0.25]]

biases = [2, 1, 3.1]

output = np.dot(weights, inputs) + biases
print(output)

[ 0.468 -1.897  1.218]


In [43]:
# To avoid confusion concerning the order in which the product is executed i.e., weights X inputs vs. inputs X weights

inputs = [4.5, 2.3, -7.4, 1.5]

weights = [[0.17, 0.59, 0.36, -0.66],
           [0.23, -0.34, 0.45, 0.12],
           [-0.67, 0.78, 0.14, 0.25]]

biases = [2, 1, 3.1]

output = np.dot(inputs, np.array(weights).T) + biases
print(output)

[ 0.468 -1.897  1.218]


-----------------------------

### Inputs in batches (matrix product)

In [45]:
# 3 sets of inputs
inputs = [[4.5, 2.3, -7.4, 1.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.17, 0.59, 0.36, -0.66],
           [0.23, -0.34, 0.45, 0.12],
           [-0.67, 0.78, 0.14, 0.25]]

biases = [2, 1, 3.1]

output = np.dot(inputs, np.array(weights).T) + biases  # Broadcasting while adding biases
print(output)

[[ 0.468 -1.897  1.218]
 [ 3.61  -0.45   6.02 ]
 [ 5.054  1.126  6.473]]


---------------

### Add another layer

In [46]:
inputs = [[4.5, 2.3, -7.4, 1.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

# First layer
weights = [[0.17, 0.59, 0.36, -0.66],
           [0.23, -0.34, 0.45, 0.12],
           [-0.67, 0.78, 0.14, 0.25]]

biases = [2, 1, 3.1]

# Second layer
weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

output_l1 = np.dot(inputs, np.array(weights).T) + biases  # output of first layer = input of second layer
output_l2 = np.dot(output_l1, np.array(weights2).T) + biases2  # output of second layer
print(output_l2)

[[-0.07862  1.13642 -2.24907]
 [ 2.434   -1.8456  -3.1995 ]
 [ 2.58426 -2.52797 -2.74327]]


---------------

### Function to build up layers

In [66]:
# np.random.seed(0)

def define_layer(inputs, n_neurons):
    
    weights = np.random.randn(inputs.shape[-1], n_neurons)  # might want to regularize the random outputs to smaller values with ( * 0.1)
    biases = np.zeros((1, n_neurons))
    
    return [weights, biases]

In [71]:
def forward_pass(inputs, layer):
    
    weights, biases = layer
    output = np.dot(inputs, weights) + biases
    
    return output

In [73]:
inputs = [[4.5, 2.3, -7.4, 1.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

# inputs = [4.5, 2.3, -7.4, 1.5]

layer1 = define_layer(np.array(inputs), 2)
out1 = forward_pass(inputs, layer1)
# print(out1)

layer2 = define_layer(out1, 5)
out2 = forward_pass(out1, layer2)
print(out2)

[[ 5.03545347  1.76834151 -2.37877239 -5.27971419  0.22097513]
 [-1.47063913  2.07529762  0.04615776  0.39115949 -0.2937936 ]
 [-2.11385545 -0.92262497  1.04371128  2.29644677 -0.07681684]]


### Activation function: Rectified Linear Unit (ReLU)

In [74]:
inputs = [0, 3, -1, 3.3, -2.7, 1.1, 2.2, -100]
output = []

# ReLU
for i in inputs:
    if i > 0:
        output.append(i)
    else:
        output.append(0)  # Or use max()
        
print(output)

[0, 3, 0, 3.3, 0, 1.1, 2.2, 0]
